### ISSUE TITLE
Really glad you made a fork! Licensing question.

### ISSUE THREAD

**Issue by nackjicholson** [nsidnev/edgeql-queries#40]
It's really cool that you've taken the project and done more with it. I'd be interested in what you needed to change in order to accomplish your needs or if you think there could be a db adapter that supports the edgedb for aiosql too.

I did notice that you changed the software license to MIT. I'm not sure that's allowed. When I forked the project from https://github.com/honza/anosql I carried forward the license @honza originally put the project under which is the [FreeBSD](https://en.wikipedia.org/wiki/BSD_licenses). My understanding is that you are free to redistribute the code but you must keep the same copyright and rights as the original license.

**Comment by nsidnev** [comment]
Hi! 

First of all, thanks for your project. It's very helpful!
Sorry for the license issue. If I need to change the license for this project to fix this problem, I will, thanks for pointing this out.

Regarding EdgeDB:
I don't think it would be difficult to create an adapter that adds support for aiosql and then put it somewhere like the `edgeql_queries.contrib.aiosql` package. 
All parsing has already been done in the custom query loader. So I think it will be sufficient to add support for the aiosql's query loader interface and the "dummy" driver, since the current loader creates the necessary functions that will run the driver methods. 
There will also be a difference in operators for queries definitions due to EdgeDB syntax.

**Comment by nackjicholson** [comment]
@nsidnev Thanks for the response and insight into how you were able to extend things for EdgeDB. That's awesome! I hope people are able to use your library to great effect!

Yes, please change the license to FreeBSD. The way I understand how to do this is by copying the exact text of the [LICENSE](https://github.com/nackjicholson/aiosql/blob/master/LICENSE) file from aiosql and basically placing your name under our names:

```
Copyright (c) 2014-2017, Honza Pokorny
Copyright (c) 2018-2020, William Vaughn
Copyright (c) 2020, YOUR NAME HERE
All rights reserved.

... yada yada yada ...
```

I'm not a software licensing expert by any means but I do think this stuff is important. Software licenses like the GPLv3, FreeBSD, and the MIT License you chose are here to protect the freedom of developers to openly collaborate and mold software to their needs. These things are what makes it possible to extend each others work in amazing ways. So, thanks for carrying it forward and I wish you the best of luck with your work!

**Comment by nsidnev** [comment]
@nackjicholson thanks for explaining what exactly I should have changed! I don't mind full licensing under FreeBSD, since they are similar to MIT (as it seemed to me).

I also added support for `aiosql` through a custom adapter, loader and queries class. 
It really turned out to be not difficult :)

> So, thanks for carrying it forward and I wish you the best of luck with your work!

Thanks! :)

**Comment by nsidnev** [comment]
@nackjicholson just merged all PRs and released a new version with FreeBSD license. If everything is complete, will you close the issue?
